apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: k8stest-imgcorp-net
  name: k8stest-imgcorp-net
spec:
  replicas: 1
  selector:
    matchLabels:
      run: k8stest-imgcorp-net
  template:
    metadata:
      labels:
        run: k8stest-imgcorp-net
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: k8stest-imgcorp-net
        image: imgregistry:32000/k8stest.imgcorp.net:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1          