apiVersion: v1
kind: Service
metadata:
    name: k8stest-imgcorp-net-service
spec:
    selector:
      run: k8stest-imgcorp-net
    type: NodePort
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30101